import type { SiteConfig } from '../types.js';
import { jsonForHtml } from '../utils/html.js';
import { fontStylesheetLinks } from './fonts.js';
import { PALETTES } from './design-system.js';

export const guidedStyles = `
:root{font-family:'Noto Sans KR','Pretendard Variable',Pretendard,'Apple SD Gothic Neo','Malgun Gothic',sans-serif;color:#172a3d;background:#f5f6f7;font-size:16px;line-height:1.6}
*{box-sizing:border-box}body{margin:0}button,input,select{font:inherit}button{cursor:pointer}button,input,select{min-height:44px}button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #2d4864;outline-offset:2px}
h1,h2,h3,p{margin-top:0}h1,h2,h3{letter-spacing:-.025em;line-height:1.35}a{color:inherit}.s-app{min-height:100vh}.s-top{height:64px;padding:0 24px;border-bottom:1px solid #d7dde5;background:#fff;display:flex;align-items:center;justify-content:space-between;gap:16px;position:sticky;top:0;z-index:20}.s-top strong{font-size:1.05rem}.s-top a{font-size:.92rem}
.s-layout{display:grid;grid-template-columns:minmax(420px,560px) minmax(0,1fr);min-height:calc(100vh - 64px)}.s-editor{padding:28px 30px 50px;overflow:auto;background:#f8f9fa;border-right:1px solid #d7dde5}.s-intro{margin-bottom:28px}.s-intro .kicker{margin:0 0 5px;font-size:.82rem;font-weight:800;letter-spacing:.08em;color:#657080}.s-intro h1{margin:0 0 8px;font-size:1.65rem}.s-intro p{margin:0;color:#657080;font-size:.94rem}
.s-section{padding:22px 0;border-top:1px solid #d7dde5}.s-section:first-of-type{border-top:0}.s-section h2{margin:0 0 14px;font-size:1.05rem}.s-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.s-field{display:block;margin:0 0 12px}.s-field>span{display:block;margin-bottom:5px;font-size:.84rem;font-weight:700;color:#455260}.s-field input,.s-field select{width:100%;border:1px solid #aeb8c3;border-radius:6px;background:#fff;padding:0 11px;color:#172a3d}.s-field input[type=file]{padding:8px;min-height:50px;font-size:.84rem}.s-field small{display:block;margin-top:5px;color:#7a8592;font-size:.78rem;line-height:1.45}.s-fixed{padding:12px 14px;background:#eef1f4;border:1px solid #d7dde5;border-radius:6px;color:#455260;font-size:.85rem}.s-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:22px}.s-btn{min-height:46px;padding:0 16px;border:1px solid #8c98a5;border-radius:6px;background:#fff;color:#172a3d;font-weight:700}.s-btn-primary{background:#2d4864;color:#fff;border-color:#2d4864}.s-status{margin-top:12px;min-height:24px;color:#526170;font-size:.84rem;white-space:pre-line}
.s-preview{position:sticky;top:64px;height:calc(100vh - 64px);background:#e6e9ed;padding:18px;display:flex;flex-direction:column;min-width:0}.s-preview[data-expanded=true]{position:fixed;inset:0;top:0;height:100dvh;z-index:100;padding:14px;background:#e6e9ed}.s-preview-bar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.s-preview-bar>strong{font-size:.95rem}.s-preview-tools{display:flex;gap:7px;align-items:center}.s-preview-tools button{min-height:38px;padding:0 11px;border:1px solid #98a4b1;border-radius:6px;background:#fff;font-size:.82rem}.s-preview-tools button[aria-pressed=true]{background:#2d4864;color:#fff;border-color:#2d4864}.s-close{display:none!important}.s-preview[data-expanded=true] .s-close{display:inline-flex!important}.s-preview[data-expanded=true] .s-expand{display:none}.s-mat{flex:1;min-height:0;overflow:hidden;display:flex;align-items:flex-start;justify-content:center}.s-canvas{position:relative;flex:0 0 auto;background:#fff;box-shadow:0 10px 28px rgba(20,30,40,.16)}.s-frame{position:absolute;inset:0 auto auto 0;border:0;background:#fff;transform-origin:top left}.s-preview-note{margin:10px 0 0;color:#657080;font-size:.78rem}
@media(max-width:1100px){.s-layout{grid-template-columns:430px minmax(0,1fr)}.s-editor{padding:22px 20px}}
@media(max-width:850px){.s-layout{display:block}.s-editor{border-right:0}.s-preview{position:relative;top:0;height:72vh}.s-top{position:relative}.s-row{grid-template-columns:1fr 1fr}}
@media(max-width:620px){.s-row{grid-template-columns:1fr}.s-editor{padding:18px 16px}.s-top{padding:0 16px}}
`;

const paletteOptions = Object.entries(PALETTES)
  .map(([id, palette]) => `<option value="${id}">${palette.name}</option>`)
  .join('');

export function renderGuidedStudioPage(site: SiteConfig): string {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title>보험 페이지 설정</title>${fontStylesheetLinks(['noto-sans-kr'])}<style>${guidedStyles}</style></head><body><div class="s-app"><header class="s-top"><strong>보험 페이지 설정</strong><a href="/?site=${encodeURIComponent(site.id)}">현재 페이지 열기 ↗</a></header><main class="s-layout"><section class="s-editor"><div class="s-intro"><p class="kicker">FIXED LAYOUT</p><h1>색상과 정보만 바꾸는 설정 화면</h1><p>디자인·문구·레이아웃 선택은 제거했습니다. 현재 페이지 구조를 기준으로 값만 바꾸고 바로 미리봅니다.</p></div>
<section class="s-section"><h2>고정 디자인</h2><div class="s-fixed">레이아웃: warm-care · 글꼴: Noto Sans KR · 워터마크: 해온 기본 · 리쿠르트 포함</div></section>
<section class="s-section"><h2>색상</h2><label class="s-field"><span>색상 팔레트</span><select data-field="palette">${paletteOptions}</select></label></section>
<section class="s-section"><h2>담당자 정보</h2><div class="s-row"><label class="s-field"><span>이름</span><input data-field="agent.name" autocomplete="off"></label><label class="s-field"><span>직함</span><input data-field="agent.title" autocomplete="off"></label></div><label class="s-field"><span>소속</span><input data-field="agent.company" autocomplete="off"></label><label class="s-field"><span>프로필 사진</span><input type="file" accept="image/png,image/jpeg,image/webp" data-image="profile"><small>선택하면 미리보기에서만 바로 반영됩니다.</small></label></section>
<section class="s-section"><h2>연락처</h2><div class="s-row"><label class="s-field"><span>전화번호</span><input data-field="contact.phone" autocomplete="off"></label><label class="s-field"><span>상담 시간</span><input data-field="contact.availableHours" autocomplete="off"></label></div><label class="s-field"><span>카카오톡 오픈채팅 URL</span><input data-field="contact.kakaoUrl" autocomplete="off"></label><label class="s-field"><span>인스타그램 URL</span><input data-field="contact.instagramUrl" autocomplete="off"></label><div class="s-row"><label class="s-field"><span>이메일</span><input data-field="contact.email" autocomplete="off"></label><label class="s-field"><span>팩스</span><input data-field="contact.fax" autocomplete="off"></label></div><label class="s-field"><span>주소</span><input data-field="contact.officeAddress" autocomplete="off"></label></section>
<section class="s-section"><h2>로고</h2><label class="s-field"><span>좌상단 로고</span><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" data-image="headerLogo"><small>agent.logoImage에 반영됩니다.</small></label><label class="s-field"><span>푸터 로고</span><input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" data-image="footerLogo"><small>agent.logoMarkImage에 반영됩니다.</small></label></section>
<div class="s-actions"><button class="s-btn s-btn-primary" type="button" data-action="download">site.json 저장</button><button class="s-btn" type="button" data-action="reset">원래 값으로 되돌리기</button></div><div class="s-status" id="studio-status" role="status" aria-live="polite"></div></section>
<section class="s-preview" id="studio-preview" data-expanded="false" aria-label="페이지 미리보기"><div class="s-preview-bar"><strong>미리보기</strong><div class="s-preview-tools"><button type="button" data-device="desktop" aria-pressed="true">PC</button><button type="button" data-device="mobile" aria-pressed="false">모바일</button><button type="button" class="s-expand" data-action="expand">크게 보기</button><button type="button" class="s-close" data-action="close">닫기</button></div></div><div class="s-mat"><div class="s-canvas"><iframe id="studio-frame" class="s-frame" title="설정 미리보기" sandbox="allow-scripts allow-same-origin"></iframe></div></div><p class="s-preview-note">연락 버튼은 미리보기에서 실제 앱을 열지 않습니다.</p></section></main></div><script id="guided-bootstrap" type="application/json">${jsonForHtml(site)}</script><script type="module" src="/assets/guided-studio.js"></script></body></html>`;
}
