import { PALETTE_IDS, TEMPLATE_IDS, type PaletteId, type SiteConfig, type TemplateId } from "../types.js";
import { escapeHtml, jsonForHtml, safeUrl } from "../utils/html.js";
import { icon } from "../utils/icons.js";
import { clientScript } from "./client-script.js";
import { renderDemoSwitcher, renderFooter, renderHeader, renderMobileCta } from "./shared.js";
import { styles } from "./styles.js";
import { premiumStyles } from "./premium-styles.js";
import { fontStylesheetLinks, headingFontStyle } from "./fonts.js";
import { renderThemePage } from "./templates/index.js";
import { DESIGN_VERSION, TEMPLATE_META, PALETTES, paletteId, paletteStyle, resolveDesign } from "./design-system.js";
function renderHead(site:SiteConfig,request:Request):string { const url=new URL(request.url); const canonical=site.domains[0]?`https://${site.domains[0]}/`:`${url.origin}/`; const og=site.seo.ogImage?new URL(site.seo.ogImage,url.origin).toString():""; const robots=site.seo.noIndex||site.status!=="published"?"noindex,nofollow":"index,follow,max-image-preview:large"; const instagram=safeUrl(site.contact.instagramUrl); const data={"@context":"https://schema.org","@type":"Person",name:site.agent.name,jobTitle:site.agent.title,worksFor:{"@type":"Organization",name:site.agent.company},telephone:site.contact.phone,email:site.contact.email||undefined,sameAs:instagram?[instagram]:undefined,areaServed:site.agent.regions,url:canonical}; const color=PALETTES[paletteId(site)].accent; return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${escapeHtml(site.seo.title)}</title><meta name="description" content="${escapeHtml(site.seo.description)}"><meta name="robots" content="${robots}"><link rel="canonical" href="${escapeHtml(canonical)}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><meta name="theme-color" content="${color}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${escapeHtml(site.seo.title)}"><meta property="og:description" content="${escapeHtml(site.seo.description)}"><meta property="og:url" content="${escapeHtml(canonical)}">${og?`<meta property="og:image" content="${escapeHtml(og)}">`:""}<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>${fontStylesheetLinks([site.headingFont])}<script type="application/ld+json">${jsonForHtml(data)}</script>`; }
export function renderSitePage(rawSite:SiteConfig,request:Request,options:{studioPreview?:boolean}={}):string {
  const site=resolveDesign(rawSite,request);const palette=paletteId(site);
  return `<!doctype html><html lang="ko"${options.studioPreview ? ' style="scroll-behavior:auto"' : ""}><head>${renderHead(site,request)}<style>${styles}${premiumStyles}</style></head><body data-design-version="${DESIGN_VERSION}" data-layout="${site.template}" data-palette="${palette}" data-heading-font="${site.headingFont}" data-studio-preview="${Boolean(options.studioPreview)}" class="premium-page theme-${site.template} palette-${palette} font-${site.headingFont||'pretendard'}" style="${paletteStyle(palette)};${escapeHtml(headingFontStyle(site.headingFont))}">${options.studioPreview?"":renderDemoSwitcher(site)}${renderHeader(site)}${renderThemePage(site)}${renderFooter(site)}${options.studioPreview?"":renderMobileCta(site)}<script>${clientScript}</script></body></html>`;
}
function renderTemplatePreview(id:TemplateId,site:SiteConfig):string {
  const headline=site.templateContent?.[id]?.headline || site.hero.headline;
  return `<div class="template-preview preview-${id}" aria-hidden="true"><div class="preview-words"><p>${escapeHtml(TEMPLATE_META[id].purpose)}</p><strong>${escapeHtml(headline).replace(/\n/g,'<br>')}</strong><span></span></div><img src="${escapeHtml(site.agent.profileImage || '/assets/profile-placeholder.svg')}" alt="" loading="lazy" width="240" height="320"><div class="preview-modules"><i></i><i></i><i></i></div></div>`;
}
export function renderTemplateGallery(rawSite:SiteConfig,request:Request):string {
  const site=resolveDesign(rawSite,request);const requested=new URL(request.url).searchParams.get('palette');
  const selected=site.demo?.enabled && site.demo.allowTemplateSwitch && PALETTE_IDS.includes(requested as PaletteId) ? requested as PaletteId : null;
  const colors=Object.entries(PALETTES).map(([id,p])=>`<button type="submit" name="palette" value="${id}" class="palette-choice" aria-pressed="${selected===id}"><span class="swatch" style="background:${p.accent}" aria-hidden="true"></span>${escapeHtml(p.name)}</button>`).join('');
  const cards=TEMPLATE_IDS.map((id,index)=>{const meta=TEMPLATE_META[id];const palette=selected||meta.palette;const href=`/?theme=${id}${selected?'&palette='+selected:''}`;return `<article class="template-tile" data-layout="${id}" data-palette="${palette}" style="${paletteStyle(palette)}">${renderTemplatePreview(id,site)}<div class="template-copy"><span class="badge">0${index+1} · ${escapeHtml(meta.purpose)}</span><h2>${escapeHtml(meta.name)}</h2><p>${escapeHtml(meta.description)}</p><p class="palette-caption"><span class="swatch" style="background:${PALETTES[palette].accent}" aria-hidden="true"></span>${escapeHtml(PALETTES[palette].name)}</p><a class="button" href="${escapeHtml(href)}">이 조합 보기 <span aria-hidden="true">↗</span></a></div></article>`;}).join('');
  return `<!doctype html><html lang="ko"><head>${renderHead(site,request)}<style>${styles}${premiumStyles}</style></head><body data-design-version="${DESIGN_VERSION}" class="premium-page gallery-page font-${site.headingFont}" style="${paletteStyle(paletteId(site))};${escapeHtml(headingFontStyle(site.headingFont))}"><main class="container" id="main"><header class="simple-header gallery-header"><a href="/">← 상담 페이지로 돌아가기</a><p class="eyebrow">ATELIER · 상담 페이지 샘플</p><h1>좋은 인상을 만드는,<br>나만의 구성.</h1><p>여백과 서체, 사진과 이야기의 순서를 살펴보세요. DIY에서는 섹션별 패턴을 고르고 나만의 원고를 넣을 수 있습니다.</p><p><a class="button" href="/studio">내 페이지 만들기 ↗</a></p></header><form class="palette-picker" action="/templates" method="get"><fieldset><legend>샘플 색상 고르기</legend><div class="palette-options"><button class="palette-choice" type="submit" name="palette" value="recommended" aria-pressed="${!selected}">배치별 추천 색상</button>${colors}</div></fieldset></form><section class="template-gallery" aria-label="배치 샘플 5가지">${cards}</section></main>${renderFooter(site)}</body></html>`;
}
export function renderPrivacyPage(site:SiteConfig,request:Request):string { return `<!doctype html><html lang="ko"><head>${renderHead(site,request)}<style>${styles}${premiumStyles}</style></head><body class="premium-page policy-body font-pretendard" style="${paletteStyle(paletteId(site))};${escapeHtml(headingFontStyle(site.headingFont))}"><main class="privacy-page"><div class="container"><header class="simple-header"><a href="/">${icon("chevron",18)} 홈페이지로 돌아가기</a><p>PRIVACY POLICY</p><h1>개인정보처리방침</h1><span>현재 신청 화면은 시연용입니다. 개인정보는 저장하거나 전송하지 않습니다.</span></header><article class="policy-card"><h2>1. 수집 항목</h2><p>이름, 연락처, 상담 희망 내용, 개인정보 수집·이용 동의 여부를 수집할 수 있습니다.</p><h2>2. 이용 목적</h2><p>상담 요청 확인, 연락, 일정 조율 및 상담 관련 안내에만 이용합니다.</p><h2>3. 보유 기간</h2><p>${escapeHtml(site.compliance.privacyRetentionPeriod)}</p><h2>4. 동의 거부 권리</h2><p>개인정보 제공에 동의하지 않을 수 있으나 상담 신청 기능 이용이 제한될 수 있습니다.</p><h2>5. 개인정보 담당</h2><p>${escapeHtml(site.compliance.privacyOfficer)}</p>${site.demo?.enabled?"<h2>데모 안내</h2><p>현재 예시 페이지는 서버 요청, 이메일, 카카오톡 전송과 브라우저 저장소를 사용하지 않습니다. 입력 내용은 화면 확인에만 사용하고 완료 또는 페이지 이탈 시 지웁니다. 아래 수집 항목과 목적은 실제 운영 전 검토할 초안입니다.</p>":""}</article></div></main>${renderFooter(site)}</body></html>`; }
export function renderNotFoundPage():string { return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>사이트를 찾을 수 없습니다</title><style>${styles}${premiumStyles}</style></head><body class="policy-body"><main class="not-found-page"><div class="container"><header class="simple-header"><p>404</p><h1>연결된 홈페이지를<br>찾을 수 없습니다.</h1><span>도메인 설정 또는 사이트 게시 상태를 확인해 주세요.</span></header></div></main></body></html>`; }
