import { TEMPLATE_IDS, type HeadingFont, type SiteConfig, type TemplateId } from "../types.js";
import { escapeHtml, jsonForHtml, safeHexColor, safeUrl } from "../utils/html.js";
import { icon } from "../utils/icons.js";
import { clientScript } from "./client-script.js";
import { renderCustomizationBand, renderDemoSwitcher, renderFooter, renderHeader, renderMobileCta } from "./shared.js";
import { styles } from "./styles.js";
import { renderThemePage } from "./templates/index.js";
import { TEMPLATE_META } from "./design-system.js";
const THEME_META = Object.fromEntries(Object.entries(TEMPLATE_META).map(([id, value]) => [id, { ...value, accent: "#2454C6", headingFont: "pretendard" as HeadingFont }])) as Record<TemplateId, { name:string; purpose:string; description:string; accent:string; headingFont:HeadingFont }>;
function cloneWithPreviewTheme(site:SiteConfig, request:Request):SiteConfig { if(!site.demo?.allowTemplateSwitch)return site; const requested=new URL(request.url).searchParams.get("theme"); if(!requested||!TEMPLATE_IDS.includes(requested as TemplateId))return site; const template=requested as TemplateId; const meta=THEME_META[template]; return {...site,template,accentColor:meta.accent,headingFont:meta.headingFont}; }
function renderHead(site:SiteConfig,request:Request):string { const url=new URL(request.url); const canonical=site.domains[0]?`https://${site.domains[0]}/`:`${url.origin}/`; const og=site.seo.ogImage?new URL(site.seo.ogImage,url.origin).toString():""; const robots=site.seo.noIndex||site.status!=="published"?"noindex,nofollow":"index,follow,max-image-preview:large"; const instagram=safeUrl(site.contact.instagramUrl); const data={"@context":"https://schema.org","@type":"Person",name:site.agent.name,jobTitle:site.agent.title,worksFor:{"@type":"Organization",name:site.agent.company},telephone:site.contact.phone,email:site.contact.email||undefined,sameAs:instagram?[instagram]:undefined,areaServed:site.agent.regions,url:canonical}; const meta=THEME_META[site.template]; const color=safeHexColor(site.accentColor,meta.accent); return `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${escapeHtml(site.seo.title)}</title><meta name="description" content="${escapeHtml(site.seo.description)}"><meta name="robots" content="${robots}"><link rel="canonical" href="${escapeHtml(canonical)}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><meta name="theme-color" content="${color}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${escapeHtml(site.seo.title)}"><meta property="og:description" content="${escapeHtml(site.seo.description)}"><meta property="og:url" content="${escapeHtml(canonical)}">${og?`<meta property="og:image" content="${escapeHtml(og)}">`:""}<link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.css"><script type="application/ld+json">${jsonForHtml(data)}</script>`; }
export function renderSitePage(rawSite:SiteConfig,request:Request):string { const site=cloneWithPreviewTheme(rawSite,request); const meta=THEME_META[site.template]; const accent=safeHexColor(site.accentColor,meta.accent); const font="font-pretendard"; return `<!doctype html><html lang="ko"><head>${renderHead(site,request)}<style>${styles}</style></head><body data-design-version="calm-trust-v4" class="theme-${site.template} ${font}" style="--user-accent:${accent}">${renderHeader(site)}${renderDemoSwitcher(site)}${renderThemePage(site)}${renderCustomizationBand(site)}${renderFooter(site)}${renderMobileCta(site)}<script>${clientScript}</script></body></html>`; }
function renderTemplatePreview(id:TemplateId,site:SiteConfig):string {
  return `<div class="template-preview preview-${id}" aria-hidden="true"><div class="preview-words"><p>${escapeHtml(TEMPLATE_META[id].name)}</p><strong>보험을 이해하는<br>편안한 시작.</strong><span></span></div><img src="${escapeHtml(site.agent.profileImage || '/assets/profile-placeholder.svg')}" alt="" loading="lazy" width="240" height="320"></div>`;
}
export function renderTemplateGallery(site:SiteConfig,request:Request):string {
  const cards=TEMPLATE_IDS.map((id)=>{const meta=TEMPLATE_META[id];return `<article class="template-tile">${renderTemplatePreview(id,site)}<div class="template-copy"><span class="badge">${escapeHtml(meta.purpose)}</span><h2>${escapeHtml(meta.name)}</h2><p>${escapeHtml(meta.description)}</p><a class="button button-secondary" href="/?theme=${id}">${escapeHtml(meta.name)} 샘플 보기 <span aria-hidden="true">↗</span></a></div></article>`;}).join('');
  return `<!doctype html><html lang="ko"><head>${renderHead(site,request)}<style>${styles}</style></head><body><main class="container"><header class="simple-header"><a href="/">← 상담 페이지로 돌아가기</a><p class="eyebrow">Calm Trust · 2026 디자인 제안</p><h1>하나의 신뢰 기준,<br>다섯 가지 상담의 시작.</h1><p>큰 글씨, 명확한 정보, 여유 있는 선택. 동일한 접근성 기준 안에서 상담 목적에 맞는 구성을 고릅니다. 모든 상담 신청은 전송 없는 샘플입니다.</p></header><section class="template-gallery" aria-label="디자인 샘플 5가지">${cards}</section></main></body></html>`;
}
export function renderPrivacyPage(site:SiteConfig,request:Request):string { return `<!doctype html><html lang="ko"><head>${renderHead(site,request)}<style>${styles}</style></head><body class="policy-body font-pretendard"><main class="privacy-page"><div class="container"><header class="simple-header"><a href="/">${icon("chevron",18)} 홈페이지로 돌아가기</a><p>PRIVACY POLICY</p><h1>개인정보처리방침</h1><span>현재 신청 화면은 시연용입니다. 개인정보는 저장하거나 전송하지 않습니다.</span></header><article class="policy-card"><h2>1. 수집 항목</h2><p>이름, 연락처, 상담 희망 내용, 개인정보 수집·이용 동의 여부를 수집할 수 있습니다.</p><h2>2. 이용 목적</h2><p>상담 요청 확인, 연락, 일정 조율 및 상담 관련 안내에만 이용합니다.</p><h2>3. 보유 기간</h2><p>${escapeHtml(site.compliance.privacyRetentionPeriod)}</p><h2>4. 동의 거부 권리</h2><p>개인정보 제공에 동의하지 않을 수 있으나 상담 신청 기능 이용이 제한될 수 있습니다.</p><h2>5. 개인정보 담당</h2><p>${escapeHtml(site.compliance.privacyOfficer)}</p>${site.demo?.enabled?"<h2>데모 안내</h2><p>현재 예시 페이지는 서버 요청, 이메일, 카카오톡 전송과 브라우저 저장소를 사용하지 않습니다. 입력 내용은 화면 확인에만 사용하고 완료 또는 페이지 이탈 시 지웁니다. 아래 수집 항목과 목적은 실제 운영 전 검토할 초안입니다.</p>":""}</article></div></main></body></html>`; }
export function renderNotFoundPage():string { return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>사이트를 찾을 수 없습니다</title><style>${styles}</style></head><body class="policy-body"><main class="not-found-page"><div class="container"><header class="simple-header"><p>404</p><h1>연결된 홈페이지를<br>찾을 수 없습니다.</h1><span>도메인 설정 또는 사이트 게시 상태를 확인해 주세요.</span></header></div></main></body></html>`; }
