export const premiumStyles = `
/* Atelier: quiet surfaces, editorial typography and independently chosen sections. */
.premium-page{background:var(--paper);color:var(--ink);font-size:1.125rem;line-height:1.85}
.premium-page .container{width:min(1240px,calc(100% - 5rem))}
.premium-page h1,.premium-page h2,.premium-page h3{font-weight:500;letter-spacing:-.035em;line-height:1.5}
.font-noto-serif-kr h1,.font-noto-serif-kr h2,.font-noto-serif-kr .brand strong,.font-noto-serif-kr .adviser-signature>strong{font-family:'Noto Serif KR',serif;font-weight:400;letter-spacing:-.045em}
.premium-page h1{font-size:clamp(2.5rem,4vw,3.6rem);line-height:1.5}.premium-page h2{font-size:clamp(2rem,2.7vw,2.65rem)}.premium-page h3{font-size:1.3rem}
.premium-page .eyebrow{font-size:1rem;letter-spacing:.07em;font-weight:500;margin-bottom:1.35rem;color:var(--accent)}
.premium-page .button{border-radius:2px;font-weight:500;gap:1.8rem;padding:1rem 1.45rem;background:var(--accent);color:#fff;min-height:3.6rem}
.premium-page .button:hover{background:var(--accent-hover)}.premium-page .button-secondary{background:transparent;color:var(--accent)}
.premium-page .button-small{padding:.55rem 1.1rem;min-height:3rem}.premium-page .text-link{font-weight:400;text-decoration:none;border-bottom:1px solid var(--input);gap:1.75rem;min-height:3rem}
.premium-page .section{padding-block:6.5rem}.premium-page .section-heading{margin-bottom:3rem;gap:3rem}.premium-page .section-heading>p{max-width:22rem;font-size:1rem}
.premium-page .site-header{background:var(--paper);border-bottom:1px solid var(--line)}.premium-page .header-inner{min-height:7rem}.premium-page .brand strong{font-size:1.55rem}.premium-page .brand-service{font-family:'Pretendard Variable',Pretendard,sans-serif;font-size:1rem;margin-left:.65rem}.premium-page .brand-sub{font-size:1rem;margin-top:.1rem}.premium-page .desktop-nav{gap:2rem}.premium-page .desktop-nav>a{font-size:1rem}
.premium-page .sample-bar{background:#ECEEE8;color:#243D35;border-bottom:1px solid #D3D8CF;position:relative;z-index:50}.premium-page .sample-inner{display:flex;padding-block:.7rem;gap:1.5rem;flex-wrap:wrap}.studio-wordmark{text-decoration:none;font-family:Georgia,serif;letter-spacing:.15em;font-size:1.15rem;display:flex;align-items:center;gap:1rem}.studio-wordmark>span{font-family:'Pretendard Variable',Pretendard,sans-serif;font-size:1rem;letter-spacing:0}.sample-label{font-size:1rem;color:#56655E;margin-left:auto}.sample-actions{display:flex;gap:1.5rem;align-items:center;font-size:1rem}.studio-start{display:inline-flex;gap:1rem;align-items:center;text-decoration:none;min-height:2.75rem;border-bottom:1px solid #56655E}.sample-settings{position:relative}.sample-settings summary{cursor:pointer;min-height:2.75rem;display:flex;align-items:center;list-style:none}.sample-settings summary::after{content:'+';margin-left:.6rem}.sample-settings[open] summary::after{content:'−'}.sample-settings:not([open]) .design-controls{display:none}.premium-page .sample-settings .design-controls{position:absolute;top:calc(100% + .8rem);right:0;width:28rem;max-width:calc(100vw - 3rem);background:#fff;color:#243D35;padding:1.5rem;border:1px solid #CDD5CC;box-shadow:0 16px 35px #183D3610;display:grid;grid-template-columns:1fr 1fr;z-index:60;margin:0}.premium-page .design-controls label{color:#53645A}.premium-page .design-controls select{font-size:1rem;max-width:100%}.premium-page .design-controls .button{color:white;background:#244C41}.premium-page .sample-bar :focus-visible{outline-color:#244C41}
.premium-page .premium-hero{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:4.5rem;padding-block:5rem 5.5rem;border:0;align-items:center;color:var(--ink);background:transparent;text-align:left}
.premium-page .hero-description{font-size:1.125rem;line-height:1.95;max-width:30rem;margin-top:1.8rem}.premium-page .hero-actions{gap:1.25rem 1.75rem;margin-top:2rem}.premium-page .hero-note{font-size:1rem;margin-top:1rem;color:var(--muted)}
.adviser-signature{display:flex;align-items:center;gap:1.5rem;margin-top:2.3rem}.adviser-signature>strong{font-size:1.65rem;letter-spacing:.02em}.adviser-signature>span{font-size:1rem;line-height:1.6;color:var(--muted);padding-left:1.5rem;border-left:1px solid var(--line)}
.hero-visual{position:relative;padding-bottom:3rem;min-width:0}.hero-scene{margin:0}.hero-scene>img{width:100%;height:32rem;object-fit:cover;object-position:55% 50%}.hero-scene figcaption{font-size:1rem;position:absolute;bottom:0;right:0;color:var(--muted)}.hero-adviser{position:absolute;display:flex;align-items:center;gap:1.25rem;background:var(--paper);padding:1.1rem 1.75rem 1.1rem 0;left:-1.75rem;bottom:2.5rem;max-width:calc(100% + 1rem);border-top:1px solid var(--line)}.hero-adviser>img{width:5.5rem;height:6.4rem;object-fit:cover;object-position:50% 15%}.hero-adviser p,.hero-adviser span{font-size:1rem;display:block}.hero-adviser strong{font-size:1.2rem;font-weight:500;display:block;margin:.15rem 0}
.premium-page .portrait-figure{max-width:29rem;justify-self:end;border-bottom:1px solid var(--line);padding-bottom:1.3rem}.portrait-figure>img{width:100%;aspect-ratio:4/4.7;object-fit:cover;object-position:50% 18%}.portrait-figure figcaption{margin-top:1.25rem;display:flex;justify-content:space-between;gap:1rem;font-size:1rem}.portrait-figure figcaption>span{letter-spacing:.1em;color:var(--muted)}.portrait-figure figcaption>strong{font-weight:500}
.premium-page .hero-statement{grid-template-columns:1fr;text-align:center;gap:2.5rem;max-width:1040px}.hero-statement .hero-description,.hero-statement .hero-copy{margin-inline:auto}.hero-statement .hero-description{max-width:41rem}.hero-statement .hero-actions,.hero-statement .adviser-signature{justify-content:center}.hero-statement .adviser-signature{display:none}.hero-statement-person{display:flex;align-items:center;text-align:left;gap:1.2rem;justify-self:center}.hero-statement-person>img{width:5.5rem;height:6.3rem;object-fit:cover;object-position:50% 15%}.hero-statement-person p,.hero-statement-person span{display:block;font-size:1rem}.hero-statement-person strong{font-size:1.1rem;font-weight:500}
.premium-page .trust-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:2rem;padding-block:1.7rem;border-block:1px solid var(--line)}.premium-page .trust-strip p{font-size:1rem;color:var(--muted);border-left:0;padding:0;text-align:center}.premium-page .trust-strip p+p{border-left:1px solid var(--line)}
.premium-page .service-grid{display:grid;gap:0;border-top:1px solid var(--input)}.premium-page .service-card,.premium-page .service-card:first-child,.premium-page .service-card:nth-child(3){padding:1.8rem 0;border:0;border-bottom:1px solid var(--line);display:grid;gap:1.3rem;min-width:0}.premium-page .service-card h3,.premium-page .service-card .section-index,.premium-page .service-card p{margin:0}.premium-page .service-card p{font-size:1.125rem;color:var(--muted)}.premium-page .section-index{font-size:1rem;font-family:Georgia,serif;color:var(--accent)}.service-link{display:flex;min-width:2.75rem;min-height:2.75rem;align-items:center;justify-content:center;align-self:center;text-decoration:none}
.premium-page .services-list{grid-template-columns:1fr}.premium-page .services-list .service-card{grid-template-columns:3.5rem minmax(0,.85fr) minmax(0,1.3fr) 3rem;align-items:center}
.premium-page .services-cards{grid-template-columns:repeat(3,minmax(0,1fr));gap:2rem;border-top:0}.premium-page .services-cards .service-card{display:flex;flex-direction:column;border-top:1px solid var(--input);padding-top:1.5rem}.services-cards .service-link{align-self:flex-start;margin-top:auto}.premium-page .services-split{grid-template-columns:1.1fr 1fr;gap:0 3.5rem;border-top:0}.premium-page .services-split .service-card{grid-template-columns:2rem 1fr auto}.services-split .service-card h3{grid-column:2}.services-split .service-card p{grid-column:2}.services-split .service-card .service-link{grid-column:3;grid-row:1/3}.premium-page .services-split .service-card:first-child{grid-row:span 6;display:flex;flex-direction:column;background:var(--tint);padding:2.5rem;border:0;justify-content:center}.services-split .service-card:first-child h3{font-size:1.8rem}.services-split .service-card:first-child .service-link{align-self:flex-start}
.premium-page .about-section{background:var(--tint);color:var(--ink)}.premium-page .about-section p,.premium-page .about-section dt{color:var(--muted)}.premium-page .about-section .eyebrow{color:var(--accent)}.premium-page .about-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:5rem;align-items:start}.premium-page .about-section .philosophy{color:var(--muted);font-size:1rem;margin-top:1.5rem;padding-left:1.2rem;border-left:1px solid var(--accent)}.premium-page .about-copy>p{font-size:1.125rem;line-height:2}.premium-page .agent-facts{margin-top:2.3rem}.premium-page .agent-facts>div{grid-template-columns:6.5rem 1fr;border-color:var(--line);padding:.7rem 0}.premium-page .agent-facts dd{font-size:1rem}.premium-page .agent-facts dt{font-size:1rem}.about-portrait>img{width:100%;max-height:38rem;object-fit:cover;object-position:50% 16%}.about-portrait figcaption{font-size:1rem;margin-top:1rem;color:var(--muted)}.about-profile .about-copy{margin-top:2rem}.premium-page .about-quote{grid-column:1/-1;max-width:850px;margin:auto;text-align:center}.about-quote .about-heading .philosophy{display:none}.about-quote blockquote{font-family:'Noto Serif KR',serif;font-size:1.75rem;line-height:1.9;margin:2rem 0;padding-block:2rem;border-block:1px solid var(--input)}.about-quote .adviser-signature{justify-content:center}.about-quote .agent-facts{text-align:left}
.premium-page .process-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:2.5rem}.premium-page .process-grid li{display:flex;flex-direction:column;border-top:1px solid var(--input);padding-top:1.5rem;gap:1.2rem;min-width:0}.premium-page .process-number{font-family:Georgia,serif;font-size:2.5rem;font-weight:400;line-height:1.3;margin:0;color:var(--accent)}.premium-page .process-grid h3{margin-bottom:.65rem}.premium-page .process-grid p{font-size:1.125rem}.premium-page .process-timeline{display:block;border-top:1px solid var(--input)}.premium-page .process-timeline li{display:grid;grid-template-columns:5rem 1fr;border-top:0;border-bottom:1px solid var(--line);padding-block:1.8rem;gap:2rem}.process-timeline li>div{display:grid;grid-template-columns:minmax(0,.65fr) minmax(0,1.35fr);gap:2rem;align-items:center}.premium-page .process-timeline h3{margin:0}
.premium-page .review-section{background:var(--tint);border-block:1px solid var(--line)}.premium-page .review-grid{gap:2.5rem}.premium-page .review-card{padding:1.5rem 0 0;background:transparent;border-top:1px solid var(--input);color:var(--ink)}.premium-page .review-card .badge{color:var(--muted);border:0;padding:0;font-size:1rem;font-weight:400}.premium-page .review-card blockquote{font-size:1.2rem;line-height:1.9}.premium-page .review-card figcaption{font-size:1rem}.premium-page .review-notice{color:var(--muted)}
.premium-page .faq-section{display:grid;grid-template-columns:minmax(0,.75fr) minmax(0,1.25fr);gap:4rem}.premium-page .faq-list{border-top:1px solid var(--input)}.premium-page .faq-list details{background:transparent;padding:0;border-bottom:1px solid var(--line)}.premium-page .faq-list summary{padding:1.4rem 0;font-size:1.125rem;font-weight:500}.premium-page .faq-list details[open]{background:transparent}.premium-page .faq-list details>p{padding-left:2.5rem;font-size:1.125rem}.premium-page .faq-columns{grid-template-columns:1fr}.premium-page .faq-columns .faq-list{display:grid;grid-template-columns:1fr 1fr;column-gap:3rem;border-top:0}.faq-columns details{border-top:1px solid var(--input)}
.premium-page .focus-section{border-bottom:1px solid var(--line)}.premium-page .focus-grid article{background:transparent;color:var(--ink);padding:1.5rem 0 0;border-top:1px solid var(--input)}.premium-page .focus-grid p{color:var(--muted)}.premium-page .focus-grid .section-index{display:block;color:var(--accent)}
.premium-page .contact-section{background:var(--tint);border-top:1px solid var(--line)}.premium-page .contact-grid{gap:5rem;grid-template-columns:minmax(0,.85fr) minmax(0,1.15fr)}.premium-page .consultation-form{border:1px solid var(--line);background:var(--paper);padding:2rem}.premium-page .form-intro .badge{font-weight:500;color:var(--accent)}.premium-page .contact-person{margin-block:2rem}.premium-page .topic-option{border-color:var(--input)}.premium-page .topic-option:has(input:checked){border-color:var(--accent)}.premium-page .form-actions{gap:1rem}.premium-page .contact-copy{padding:0}
.premium-page .site-footer{background:var(--dark);padding-block:4.5rem 2rem;color:#F7F6F0}.premium-page .footer-top{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,.55fr);gap:4rem;align-items:start;padding-bottom:3.25rem;border-bottom:1px solid #D3DFD033}.premium-page .footer-identity h2{font-size:1.9rem;line-height:1.5;margin-bottom:1.4rem}.premium-page .footer-identity p{font-size:1.125rem;color:#D6E0D9;line-height:1.9}.premium-page .footer-identity .footer-note{font-size:1rem;color:#C0CFC5;margin-top:1rem}.footer-contact{justify-self:end}.footer-contact>div{display:flex;gap:.6rem;font-size:1.125rem;color:#D6E0D9}.footer-contact dt{flex-shrink:0}.footer-contact dd{min-width:0;overflow-wrap:anywhere}.premium-page .footer-legal p{color:#C0CFC5;font-size:1rem}.footer-bottom{display:flex;justify-content:space-between;gap:2rem;margin-top:1.4rem;align-items:center}.footer-bottom a{font-size:1rem;min-height:2.75rem;display:flex;align-items:center}.premium-page .footer-columns .footer-top{grid-template-columns:1fr 1fr 1fr}.footer-business p{font-size:1rem;color:#D6E0D9}.footer-columns .footer-contact{justify-self:start;padding-left:2rem;border-left:1px solid #D3DFD033}.premium-page .footer-minimal .footer-top{display:block;text-align:center}.footer-minimal .footer-contact{display:flex;flex-wrap:wrap;justify-content:center;gap:1rem 2rem;margin-top:2rem}.footer-minimal .footer-bottom{justify-content:center;flex-wrap:wrap}
.ornament-grid .services-section{background-image:linear-gradient(90deg,transparent calc(100% - 1px),color-mix(in srgb,var(--line) 45%,transparent) 1px);background-size:33.333% 100%}.ornament-none .trust-strip,.ornament-none .section-index{display:none}.density-compact .section{padding-block:4rem}.density-compact .premium-hero{padding-block:3rem}
.premium-page .gallery-header{max-width:60rem}.premium-page .gallery-header h1{font-size:clamp(2.3rem,4vw,3.6rem)}.premium-page .template-tile{border:0;border-bottom:1px solid var(--line);background:var(--paper)}.premium-page .template-copy{padding:2rem 0}.premium-page .template-preview{background:var(--tint);color:var(--ink)}.premium-page .preview-words p{color:var(--muted)}.premium-page .preview-modules i{border-color:var(--input)}
@media(max-width:1100px){.premium-page .premium-hero{gap:3rem}.premium-page .desktop-nav{gap:1.2rem}.premium-page .hero-scene>img{height:29rem}.premium-page .about-grid,.premium-page .contact-grid{gap:3rem}.studio-wordmark>span{display:none}}
@media(max-width:900px){.premium-page .container{width:calc(100% - 3rem)}.premium-page .section{padding-block:4.5rem}.premium-page .header-inner{min-height:6rem}.premium-page .premium-hero{grid-template-columns:minmax(0,1fr) minmax(0,.9fr);gap:2rem;padding-block:3rem}.premium-page .hero h1{font-size:2.5rem}.premium-page .hero-scene>img{height:28rem}.hero-adviser{position:relative;left:0;bottom:auto;padding:1rem 0 0;max-width:100%;margin-top:1rem}.hero-visual{padding-bottom:0}.hero-scene figcaption{display:none}.premium-page .hero-statement{grid-template-columns:1fr}.premium-page .about-grid,.premium-page .contact-grid{grid-template-columns:1fr;gap:2.5rem}.about-profile .about-portrait{max-width:28rem}.premium-page .faq-section{grid-template-columns:1fr;gap:2rem}.premium-page .services-list .service-card{grid-template-columns:2rem minmax(0,.8fr) minmax(0,1fr) 2rem;gap:1rem}.premium-page .services-cards{grid-template-columns:1fr 1fr}.premium-page .services-split{gap:0 2rem}.sample-label{display:none}.premium-page .sample-inner{justify-content:space-between}.sample-actions{gap:1.25rem}.premium-page .footer-top{gap:2rem;grid-template-columns:1.2fr 1fr}.footer-contact>div{display:block}.premium-page .mobile-menu nav{background:var(--paper)} }
@media(max-width:650px){
 .premium-page .container{width:calc(100% - 2.5rem)}.premium-page .section{padding-block:3.5rem}.premium-page .section-heading{margin-bottom:2rem;display:block}.premium-page h2{font-size:2rem;line-height:1.6}.premium-page .eyebrow{letter-spacing:.03em;margin-bottom:1rem}.premium-page .header-inner{min-height:5.5rem}.premium-page .brand strong{font-size:1.3rem}.premium-page .brand-service{margin-left:.35rem}.premium-page .brand-sub{font-size:1rem}.premium-page .button{padding:.85rem 1.05rem;gap:1rem;min-height:3.5rem}
 .premium-page .sample-inner{gap:.4rem 1rem;padding-block:.65rem}.studio-wordmark{font-size:1rem;letter-spacing:.1em}.sample-actions{gap:1rem}.sample-settings>summary{font-size:1rem}.studio-start{font-size:1rem}.premium-page .sample-settings .design-controls{position:fixed;left:1.25rem;right:1.25rem;top:4.4rem;width:auto;max-width:none;padding:1.1rem}.sample-label{display:none}
 .premium-page .premium-hero{grid-template-columns:1fr;gap:2.5rem;padding-block:2.75rem}.premium-page .hero h1{font-size:2.3rem;line-height:1.55}.premium-page .hero-description{font-size:1.125rem;line-height:1.8;margin-top:1.3rem}.premium-page .hero-actions{gap:1rem;margin-top:1.5rem}.premium-page .hero-note{font-size:1rem}.hero-copy>.adviser-signature{display:none}.premium-page .hero-scene>img{height:auto;aspect-ratio:1.25;object-position:60% 50%}.hero-adviser{gap:1rem;padding-top:1rem}.hero-adviser>img{width:4rem;height:4.75rem}.hero-adviser>div{display:grid;grid-template-columns:auto 1fr;gap:0 .75rem}.hero-adviser p{grid-column:1/-1}.hero-adviser strong{margin:0}.hero-adviser span{align-self:center}.premium-page .portrait-figure{max-width:100%;width:100%}.portrait-figure>img{aspect-ratio:1.1;max-height:28rem;object-position:50% 15%}.portrait-figure figcaption{flex-wrap:wrap}.premium-page .hero-statement-person{justify-self:center}
 .premium-page .trust-strip{grid-template-columns:1fr;gap:.6rem;padding-block:1.3rem}.premium-page .trust-strip p{text-align:left;padding-left:1rem;border-left:1px solid var(--input)}.premium-page .trust-strip p+p{border-left:1px solid var(--input)}
 .premium-page .services-list .service-card{grid-template-columns:2rem 1fr 2rem;gap:.65rem 1rem;padding-block:1.5rem}.services-list .service-card h3{grid-column:2}.services-list .service-card p{grid-column:2}.services-list .service-link{grid-column:3;grid-row:1/3}.premium-page .services-cards,.premium-page .services-split{grid-template-columns:1fr;gap:1rem}.premium-page .services-cards .service-card{padding-top:1.5rem}.premium-page .services-split .service-card:first-child{grid-row:auto;padding:1.5rem}.services-split .service-card:first-child h3{font-size:1.5rem}.premium-page .about-grid{gap:2rem}.premium-page .agent-facts>div{grid-template-columns:minmax(0,.65fr) minmax(0,1.35fr);gap:1rem}.adviser-signature{gap:1rem}.adviser-signature>span{padding-left:1rem}.about-quote blockquote{font-size:1.4rem;text-align:left}.premium-page .about-quote{text-align:left}.about-quote .adviser-signature{justify-content:flex-start}
 .premium-page .process-grid{grid-template-columns:1fr;gap:1.5rem}.premium-page .process-grid li{display:grid;grid-template-columns:2.5rem 1fr;gap:1rem;padding-top:1.5rem}.premium-page .process-grid li>div{display:block}.premium-page .process-number{font-size:2rem}.premium-page .process-grid h3{margin-bottom:.5rem}.premium-page .process-grid p{grid-column:auto}.premium-page .review-grid{grid-template-columns:1fr;gap:2rem}.premium-page .review-card blockquote{font-size:1.125rem}.premium-page .faq-list summary{font-size:1.125rem;gap:.75rem}.premium-page .faq-list details>p{padding-left:0}.premium-page .faq-columns .faq-list{grid-template-columns:1fr}.premium-page .focus-grid{grid-template-columns:1fr;gap:1.5rem}.premium-page .consultation-form{padding:1.1rem}.premium-page .contact-grid{gap:2rem}.premium-page .contact-person{margin-block:1.5rem}.premium-page .footer-top,.premium-page .footer-columns .footer-top{display:grid;grid-template-columns:1fr;gap:2rem;padding-bottom:2.5rem}.premium-page .site-footer{padding-block:3rem 2rem}.premium-page .footer-identity h2{font-size:1.65rem;margin-bottom:1rem}.premium-page .footer-identity p,.footer-contact>div{font-size:1.125rem}.footer-contact{justify-self:start}.footer-contact>div{display:flex;gap:.6rem}.footer-columns .footer-contact{padding:0;border:0}.footer-bottom{display:block;margin-top:1.5rem}.footer-bottom a{margin-top:.75rem}.premium-page .footer-minimal .footer-top{display:block}.footer-minimal .footer-contact{display:block;text-align:left}.footer-minimal .footer-identity{text-align:left}.premium-page .section-heading>p{margin-top:1rem}.density-compact .section{padding-block:2.5rem}
}
@media(max-width:380px){.premium-page .sample-inner{display:block}.sample-actions{justify-content:space-between;margin-top:.2rem}.studio-wordmark{line-height:1.7}.premium-page .sample-settings .design-controls{top:7rem}.hero-adviser>div{display:block}.premium-page .hero-actions{display:flex;align-items:flex-start}.premium-page .hero-actions .button{width:100%}.premium-page .hero h1{font-size:2.1rem}}
@media print{.sample-bar,.mobile-cta,.header-tools,.form-actions{display:none!important}.premium-page{background:white}.premium-page .container{width:100%}.premium-page .section{padding-block:1.5rem;break-inside:avoid}.premium-page .site-footer{print-color-adjust:exact;-webkit-print-color-adjust:exact}.premium-page .premium-hero{padding-block:1rem}.premium-page .hero-scene>img{height:18rem}.premium-page h1{font-size:30pt}.premium-page h2{font-size:22pt}.premium-page .button{border:1px solid currentColor}}
`;
