import type { SiteConfig } from "../../types.js";
import { escapeHtml, nl2br } from "../../utils/html.js";
import { formatIndex, renderContactForm, renderReviewNotice, renderSocialLinks } from "../shared.js";
export function renderCleanMinimalPage(site: SiteConfig): string {
  const reviews=site.reviews??[];
  const services=site.specialties.map((item,index)=>`<article class="report-service"><span>${formatIndex(index)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.body)}</p></article>`).join("");
  const steps=site.sections.process?site.process.map((item,index)=>`<li><span>${formatIndex(index)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.body)}</p></li>`).join(""):"";
  const reviewRows=site.sections.reviews?reviews.map((r,index)=>`<article class="report-review"><span>${formatIndex(index)}</span><blockquote>${escapeHtml(r.quote)}</blockquote><footer><strong>${escapeHtml(r.author)}</strong>${r.context?`<small>${escapeHtml(r.context)}</small>`:""}${r.isExample?`<em>예시 후기</em>`:""}</footer></article>`).join(""):"";
  const faqs=site.sections.faq?site.faqs.map((item,index)=>`<details class="report-faq"${index===0?" open":""}><summary><span>${formatIndex(index)}</span><strong>${escapeHtml(item.question)}</strong><i aria-hidden="true"></i></summary><div><p>${escapeHtml(item.answer)}</p></div></details>`).join(""):"";
  return `<main class="theme-page report-page">
    <section class="report-hero" id="home"><div class="container report-hero-grid"><div class="report-hero-index"><span>PERSONAL</span><strong>INSURANCE<br>ADVISER</strong><small>PROFILE / 2026</small></div><figure class="report-portrait"><img src="${escapeHtml(site.agent.profileImage)}" alt="${escapeHtml(site.agent.name)} ${escapeHtml(site.agent.title)} 프로필" width="1086" height="1448"><figcaption>${escapeHtml(site.agent.name)} · ${escapeHtml(site.agent.company)}</figcaption></figure><div class="report-hero-copy"><p class="theme-overline">${escapeHtml(site.hero.eyebrow||site.agent.company)}</p><h1>${escapeHtml(site.hero.headline)}</h1><p>${escapeHtml(site.hero.subheadline)}</p>${site.hero.trustNote?`<blockquote>${escapeHtml(site.hero.trustNote)}</blockquote>`:""}${renderSocialLinks(site,"social-links report-social")}</div></div></section>
    <section class="report-intro section-anchor" id="about"><div class="container report-intro-grid"><div class="report-label"><span>01</span><p>ABOUT</p></div><h2>${escapeHtml(site.intro.title)}</h2><div><p>${nl2br(site.intro.body)}</p>${site.intro.philosophy?`<strong>${escapeHtml(site.intro.philosophy)}</strong>`:""}</div></div></section>
    <section class="report-services section-anchor" id="specialties"><div class="container"><header class="report-section-head"><div><span>02</span><p>SCOPE</p></div><h2>상담 가능한 항목</h2><small>권유보다 설명과 비교에 초점을 둡니다.</small></header><div class="report-service-table">${services}</div></div></section>
    ${steps?`<section class="report-process"><div class="container"><header class="report-section-head"><div><span>03</span><p>PROCESS</p></div><h2>상담 진행 순서</h2></header><ol>${steps}</ol></div></section>`:""}
    ${reviewRows?`<section class="report-reviews section-anchor" id="reviews"><div class="container"><header class="report-section-head"><div><span>04</span><p>VOICE</p></div><h2>상담 인상 기록</h2>${renderReviewNotice(site)}</header><div class="report-review-list">${reviewRows}</div></div></section>`:""}
    ${faqs?`<section class="report-faq-section section-anchor" id="faq"><div class="container"><header class="report-section-head"><div><span>05</span><p>FAQ</p></div><h2>자주 묻는 질문</h2></header><div class="report-faq-list">${faqs}</div></div></section>`:""}
    <section class="report-contact section-anchor" id="contact"><div class="container report-contact-grid"><div class="report-contact-copy"><div class="report-label"><span>06</span><p>CONTACT</p></div><h2>상담 요청</h2><p>전화와 카카오톡은 바로 연결됩니다. 상세 내용은 상담 카드에 남길 수 있습니다.</p><strong>${escapeHtml(site.contact.availableHours)}</strong>${renderSocialLinks(site,"social-links contact-social")}</div>${site.sections.contactForm?renderContactForm(site,"report-form"):""}</div></section>
  </main>`;
}
