import type { SiteConfig } from "../../types.js";
import { escapeHtml, nl2br } from "../../utils/html.js";
import { formatIndex, renderContactForm, renderReviewNotice, renderSocialLinks } from "../shared.js";
export function renderPremiumNavyPage(site: SiteConfig): string {
  const reviews=site.reviews??[];
  const services=site.specialties.map((item,index)=>`<article class="private-service"><span>${formatIndex(index)}</span><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.body)}</p></div></article>`).join("");
  const steps=site.sections.process?site.process.map((item,index)=>`<li><span>${formatIndex(index)}</span><div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.body)}</p></div></li>`).join(""):"";
  const reviewCards=site.sections.reviews?reviews.map((r,index)=>`<article class="private-review"><span>${formatIndex(index)}</span><blockquote>${escapeHtml(r.quote)}</blockquote><footer><strong>${escapeHtml(r.author)}</strong>${r.context?`<small>${escapeHtml(r.context)}</small>`:""}${r.isExample?`<em>예시 후기</em>`:""}</footer></article>`).join(""):"";
  const faqs=site.sections.faq?site.faqs.map((item,index)=>`<details class="private-faq"${index===0?" open":""}><summary><span>${formatIndex(index)}</span><strong>${escapeHtml(item.question)}</strong><i aria-hidden="true"></i></summary><p>${escapeHtml(item.answer)}</p></details>`).join(""):"";
  return `<main class="theme-page private-page">
    <section class="private-hero" id="home"><div class="private-portrait"><img src="${escapeHtml(site.agent.profileImage)}" alt="${escapeHtml(site.agent.name)} ${escapeHtml(site.agent.title)} 프로필" width="1086" height="1448"></div><div class="private-shade" aria-hidden="true"></div><div class="container private-hero-inner"><div class="private-copy"><p class="theme-overline">PRIVATE INSURANCE CONSULTING</p><h1>${escapeHtml(site.hero.headline)}</h1><p>${escapeHtml(site.hero.subheadline)}</p>${site.hero.trustNote?`<span class="private-assurance">${escapeHtml(site.hero.trustNote)}</span>`:""}${renderSocialLinks(site,"social-links private-social")}</div><aside class="private-identity"><span>ADVISER</span><strong>${escapeHtml(site.agent.name)}</strong><small>${escapeHtml(site.agent.title)} · ${escapeHtml(site.agent.company)}</small><dl><div><dt>상담 시간</dt><dd>${escapeHtml(site.contact.availableHours)}</dd></div><div><dt>상담 방식</dt><dd>예약 · 비대면</dd></div></dl></aside></div></section>
    <section class="private-intro section-anchor" id="about"><div class="container private-intro-grid"><div><p>01 · ADVISORY PRINCIPLE</p><h2>${escapeHtml(site.intro.title)}</h2></div><div><p>${nl2br(site.intro.body)}</p>${site.intro.philosophy?`<blockquote>${escapeHtml(site.intro.philosophy)}</blockquote>`:""}</div></div></section>
    <section class="private-services section-anchor" id="specialties"><div class="container"><header class="private-section-head"><p>02 · CONSULTING SCOPE</p><h2>개인의 상황과 기준에 맞춰 검토합니다.</h2></header><div class="private-service-grid">${services}</div></div></section>
    ${steps?`<section class="private-process"><div class="container private-process-grid"><header><p>03 · REVIEW PROCESS</p><h2>확인하고, 비교하고, 충분히 검토합니다.</h2></header><ol>${steps}</ol></div></section>`:""}
    ${reviewCards?`<section class="private-reviews section-anchor" id="reviews"><div class="container"><header class="private-section-head"><p>04 · CLIENT NOTES</p><h2>설명과 진행 방식에 대한 인상</h2>${renderReviewNotice(site)}</header><div class="private-review-track">${reviewCards}</div></div></section>`:""}
    ${faqs?`<section class="private-faq-section section-anchor" id="faq"><div class="container private-faq-grid"><header><p>05 · FAQ</p><h2>상담 전 확인할 질문을 정리했습니다.</h2><span>각 질문을 열어 답변을 확인하세요.</span></header><div>${faqs}</div></div></section>`:""}
    <section class="private-contact section-anchor" id="contact"><div class="container private-contact-grid"><div class="private-contact-copy"><p>06 · REQUEST A CONSULTATION</p><h2>필요한 내용을 먼저 남겨주시면 차분히 확인하겠습니다.</h2><span>${escapeHtml(site.agent.name)} · ${escapeHtml(site.contact.availableHours)}</span>${renderSocialLinks(site,"social-links contact-social")}</div>${site.sections.contactForm?renderContactForm(site,"private-form"):""}</div></section>
  </main>`;
}
